[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# SPA redirect rule - this is crucial for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for development
[[redirects]]
  from = "/api/*"
  to = "https://walmart-supply-chain-api.vercel.app/:splat"
  status = 200
  force = true
# Cache optimization for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
# Environment variables for production
[context.production.environment]
  VITE_API_URL = "https://walmart-supply-chain-api.vercel.app"
  NODE_ENV = "production"

[context.branch-deploy.environment]
  VITE_API_URL = "https://walmart-supply-chain-api.vercel.app"
  NODE_ENV = "development"
[context.deploy-preview.environment]
  VITE_API_URL = "https://walmart-supply-chain-api.vercel.app"
  NODE_ENV = "development"